### PR TITLE
Fix SCTransform umi.assay incorrect source assay labels

### LINKED ISSUE #10323: BUG: When using custom assay data from a merged object, SCTransform either does not use the right data or mislabels the resulting umi.assay slot
### Issue Description

Hi Seurat team, thank you for the work you do with this package. 

I have an integrated single cell experiment from 9 different samples. I have run both DoubletFinder and decontX on each sample individually. I stored the rounded decontX counts as an additional assay for each sample. I then merged, joined, and split layers to get proper layer names. 

I then ran SCTransform, specifying the decontX assay for use. I can see it run the SCTransform process for each sample. However checking the umi.assay slot for each SCTAssay generated, it lists only the first layer as "decontX" while the rest is RNA.

```
SCTResults(dX.seur, slot = "umi.assay")

$model1
[1] "decontX"

$model1.1
[1] "RNA"

$model1.2
[1] "RNA"

$model1.3
[1] "RNA"

$model1.4
[1] "RNA"

$model1.5
[1] "RNA"

$model1.6
[1] "RNA"

$model1.7
[1] "RNA"

$model1.8
[1] "RNA"
```

This seems related to this issue:
https://github.com/satijalab/seurat/issues/9725

I want to confirm that this is just a labeling issue and that the decontX assay was actually used for each layer and not just the first. Thanks!

### Reproducing Code Example

```R
NA
```

### Error Message

```shell

```

### Additional Comments

_No response_

### Session Info

```shell
R version 4.5.1 (2025-06-13)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 24.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.12.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.12.0  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Toronto
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggplot2_4.0.1               patchwork_1.3.2             future_1.68.0               gridExtra_2.3               tibble_3.3.1                dplyr_1.1.4                
 [7] DoubletFinder_2.0.6         decontX_1.6.0               SingleCellExperiment_1.32.0 SummarizedExperiment_1.40.0 Biobase_2.70.0              GenomicRanges_1.62.0       
[13] Seqinfo_1.0.0               IRanges_2.44.0              S4Vectors_0.48.0            BiocGenerics_0.56.0         generics_0.1.4              MatrixGenerics_1.22.0      
[19] matrixStats_1.5.0           Seurat_5.4.0                SeuratObject_5.3.0          sp_2.2-0                   

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3        rstudioapi_0.17.1         jsonlite_2.0.0            magrittr_2.0.4            spatstat.utils_3.2-0      farver_2.1.2             
  [7] fields_17.1               vctrs_0.7.0               ROCR_1.0-11               DelayedMatrixStats_1.30.0 spatstat.explore_3.6-0    htmltools_0.5.9          
 [13] S4Arrays_1.10.0           SparseArray_1.10.3        StanHeaders_2.32.10       sctransform_0.4.2         parallelly_1.46.0         KernSmooth_2.23-26       
 [19] htmlwidgets_1.6.4         ica_1.0-3                 plyr_1.8.9                plotly_4.11.0             zoo_1.8-15                igraph_2.2.1             
 [25] mime_0.13                 lifecycle_1.0.5           pkgconfig_2.0.3           Matrix_1.7-3              R6_2.6.1                  fastmap_1.2.0            
 [31] fitdistrplus_1.2-4        shiny_1.12.1              digest_0.6.39             colorspace_2.1-2          tensor_1.5.1              RSpectra_0.16-2          
 [37] irlba_2.3.5.1             pkgload_1.4.1             beachmat_2.24.0           progressr_0.18.0          spatstat.sparse_3.1-0     httr_1.4.7               
 [43] polyclip_1.10-7           abind_1.4-8               compiler_4.5.1            withr_3.0.2               inline_0.3.21             S7_0.2.1                 
 [49] fastDummies_1.7.5         QuickJSR_1.8.1            pkgbuild_1.4.8            maps_3.4.3                MASS_7.3-65               DelayedArray_0.36.0      
 [55] loo_2.9.0                 tools_4.5.1               lmtest_0.9-40             otel_0.2.0                httpuv_1.6.16             future.apply_1.20.1      
 [61] MCMCprecision_0.4.2       goftest_1.2-3             glmGamPoi_1.20.0          glue_1.8.0                nlme_3.1-168              promises_1.5.0           
 [67] grid_4.5.1                Rtsne_0.17                cluster_2.1.8.1           reshape2_1.4.5            gtable_0.3.6              spatstat.data_3.1-9      
 [73] tidyr_1.3.2               data.table_1.18.0         XVector_0.50.0            spatstat.geom_3.6-1       RcppAnnoy_0.0.22          ggrepel_0.9.6            
 [79] RANN_2.6.2                pillar_1.11.1             stringr_1.6.0             spam_2.11-1               RcppHNSW_0.6.0            later_1.4.4              
 [85] splines_4.5.1             lattice_0.22-5            survival_3.8-3            deldir_2.0-4              tidyselect_1.2.1          miniUI_0.1.2             
 [91] pbapply_1.7-4             scattermore_1.2           rstan_2.32.7              stringi_1.8.7             lazyeval_0.2.2            codetools_0.2-20         
 [97] cli_3.6.5                 uwot_0.2.4                RcppParallel_5.1.11-1     xtable_1.8-4              reticulate_1.44.1         Rcpp_1.1.1               
[103] globals_0.18.0            spatstat.random_3.4-3     png_0.1-8                 spatstat.univar_3.1-5     parallel_4.5.1            rstantools_2.5.0         
[109] dotCall64_1.2             sparseMatrixStats_1.20.0  listenv_0.10.0            viridisLite_0.4.2         scales_1.4.0              ggridges_0.5.7           
[115] purrr_1.2.1               combinat_0.0-8            rlang_1.1.7               cowplot_1.2.0
```

### PR DESCRIPTION
**Pull request by YoukaiFromAccounting**
Fixes: https://github.com/satijalab/seurat/issues/10323

Previously, SCTransform.Seurat() was hard-coded to only updated the umi.assay field for the first entry in SCTModel.list:

```{R}
slot(object = slot(object = assay.data, name = "SCTModel.list")[[1]], name = "umi.assay") <- assay
```

For objects with multiple SCT models, such as those created from multiple samples or layers, the remaining models did not have their source assay updated correctly, which would remain at the default "RNA" source assay. This would cause issues with downstream functions such as PrepSCTFindMarkers.

This simple change updates umi.assay for every model in SCTModel.list, so all SCT models consistently record the assay used to run SCTransform(). With these changes, individual SCT models should now correctly have their source assay assigned following SCTransform(). 

Reproducible example: 
```{R}
data("pbmc_small")

# Create fake Seurat object with two samples
rna_counts <- LayerData(pbmc_small, assay = "RNA", layer = "counts")
obj <- CreateSeuratObject(counts = rna_counts)
obj$sample <- rep(c("sample1", "sample2"), length.out = ncol(obj))

# Create new "decontX" assay
obj[["decontX"]] <- CreateAssayObject(counts = rna_counts)
obj[["decontX"]] <- split(obj[["decontX"]], f = obj$sample)

# Run SCTransform
obj <- SCTransform(
  object = obj,
  assay = "decontX",
  ncells = ncol(obj),
  variable.features.n = 20,
  return.only.var.genes = FALSE,
  conserve.memory = FALSE
)

# Inspect resulting SCT assay
# With these changes, there should be two SCT models model1 and model1.1, both with the
# decontX source assay (rather than an incorrect RNA source assay)
SCTResults(obj, slot = "umi.assay")
```

### CODE REVIEW

File: R/preprocessing.R [hunk 1]
```diff
@@ -4288,7 +4288,16 @@ SCTransform.Seurat <- function(
...
-  slot(object = slot(object = assay.data, name = "SCTModel.list")[[1]], name = "umi.assay") <- assay
+  
+  # Extract all SCT models stored in assay
+  sct_models <- slot(object = assay.data, name = "SCTModel.list")
+  
+  # Update umi.assay field for every SCT model 
+  for (i in seq_along(sct_models)) {
+    slot(object = sct_models[[i]], name = "umi.assay") <- assay
+  }
+  slot(object = assay.data, name = "SCTModel.list") <- sct_models
```
Comment (anashen) [inline R/preprocessing.R]:
```suggestion
  slot(object = assay.data, name = "SCTModel.list") <- lapply(sct_models, function(model) {
    slot(model, name = "umi.assay") <- assay
    model
  })
```
It'd be nice to use `lapply` here and assign directly to the slot :)

**Review by anashen — CHANGES_REQUESTED** [review]
Thanks @YoukaiFromAccounting! Added a minor suggestion but other than that everything looks good.

**Review by anashen — APPROVED** [review]
Thanks @YoukaiFromAccounting
